messages:
  itemKeepable: "&aYour Item will now be kept with you at all times!"
  itemNotKeepable: "&cYour Item will no longer be kept with you at all times!"
  playerOnly: "&cYou must be a player to run this command!"
  permissionDenied: "&cYou don't have permission to use this command!"
  reload: "&aThe config has been reloaded"

item:
  name-suffix: false
  suffix-on: " &8[&aON&8]&r"
  suffix-off: " &8[&cOFF&8]&r"
  name-prefix: false
  prefix-on: "&8[&aON&8]&r "
  prefix-off: "&r"
  lore: true
  lore-on: "&7This item is permanent"
  lore-off: "&cThis is off"