name: ItemKeeper
version: '${project.version}'
main: com.xef5000.itemkeeper.ItemKeeper
description: Keep specific items on death and restore them on respawn
author: xef5000

commands:
  keep:
    description: Keep specific items on death
    usage: /keep
    permission: itemkeeper.keep
